insert into public.allergens (name, name_no, name_sv, name_da)
values
  ('Almonds', 'Mandler', 'Mandlar', 'Mandler'),
  ('Barley', 'Bygg', 'Bygg', 'Byg'),
  ('Brazil nuts', 'Paranøtter', 'Paranötter', 'Paranødder'),
  ('Cashew nuts', 'Cashewnøtter', 'Cashewnötter', 'Cashewnødder'),
  ('Cereals', 'Korn', 'Spannmål', 'Korn'),
  ('Crustaceans', 'Skalldyr', 'Skaldjur', 'Skaldyr'),
  ('Dairy', 'Meieriprodukter', 'Mejeriprodukter', 'Mejeriprodukter'),
  ('Durum wheat', 'Durumhvete', 'Durumvete', 'Durumhvede'),
  ('Einkorn', 'Enkorn', 'Enkorn', 'Enkorn'),
  ('Emmer', 'Emmer', 'Emmer', 'Emmer'),
  ('Hazelnuts', 'Hasselnøtter', 'Hasselnötter', 'Hasselnødder'),
  ('Kamut', 'Kamut', 'Kamut', 'Kamut'),
  ('Khorasan wheat', 'Korasanhvete', 'Korasanvete', 'Korasanhvede'),
  ('Lupin', 'Lupin', 'Lupin', 'Lupin'),
  ('Macadamia nuts', 'Macadamianøtter', 'Macadamianötter', 'Macadamianødder'),
  ('Molluscs', 'Bløtdyr', 'Blötdjur', 'Bløddyr'),
  ('Nuts', 'Nøtter', 'Nötter', 'Nødder'),
  ('Oats', 'Havre', 'Havre', 'Havre'),
  ('Peanuts', 'Peanøtter', 'Jordnötter', 'Jordnødder'),
  ('Pecan nuts', 'Pekannøtter', 'Pekannötter', 'Pekannødder'),
  ('Pistachio nuts', 'Pistasjnøtter', 'Pistasjnötter', 'Pistacienødder'),
  ('Rye', 'Rug', 'Råg', 'Rug'),
  ('Spelt', 'Spelt/Dinkel', 'Spelt/Dinkel', 'Spelt/Dinkel'),
  ('Triticale', 'Triticale/Rughvete', 'Triticale/Rågvete', 'Triticale/Rughvede'),
  ('Walnuts', 'Valnøtter', 'Valnötter', 'Valnødder'),
  ('Wheat', 'Hvete', 'Vete', 'Hvede')
on conflict (name) do nothing;
